import {
	pissardiImg1x_mob,
	pissardiImg2x_mob,
	catalpaImg1x_mob,
	catalpaImg2x_mob,
	MagnolyImg1x_mob,
	MagnolyImg2x_mob,
	topolyaImg2x_desk,
	topolyaImg1x_desk,
	matsudanaImg1x_desk,
	matsudanaImg2x_desk,
	gorobynaImg1x_desk,
	gorobynaImg2x_desk,
	MagnolyImg1x_desk,
	MagnolyImg2x_desk,
	catalpaImg1x_desk,
	catalpaImg2x_desk,
	pissardiImg1x_desk,
	pissardiImg2x_desk,
} from '.';

const data = [
	{
		id: 1,
		imgMob: pissardiImg1x_mob,
		imgMobRetina: pissardiImg2x_mob,
		imgTab: pissardiImg1x_desk,
		imgTabRetina: pissardiImg2x_desk,
		title: 'Слива Піссарді',
		text: 'Піссарді високо ціниться за свої декоративні якості, протягом усього сезону листя темно-червоного або бордового забарвлення. Розмір листя, в довжину досягає 7 см. Квітне рожевим, плоди мають кислуватий присмак та будуть до смаку місцевим птахам',
		price: '...',
	},
	{
		id: 2,
		imgMob: catalpaImg1x_mob,
		imgMobRetina: catalpaImg2x_mob,
		imgTab: catalpaImg1x_desk,
		imgTabRetina: catalpaImg2x_desk,
		title: 'Катальпа бігнонієвидна',
		text: 'Дерево з широкою кроною, крупним серцеподібним листям, що досягає 15 см у довжину. Вид стійкий до низьких температур. Цвіт білого кольору та мають слабкий аромат.',
		price: '...',
	},
	{
		id: 3,
		imgMob: MagnolyImg1x_mob,
		imgMobRetina: MagnolyImg2x_mob,
		imgTab: MagnolyImg1x_desk,
		imgTabRetina: MagnolyImg2x_desk,
		title: 'Магнолія Суланджа рожева',
		text: 'Невелике швидкоростуче дерево з округлою формою крони та довгастим листям темно-зеленого кольору зверху та світлішим знизу. Цвіт рожевого кольору з’являється в квітні-травні, має чашоподібну форму, діаметром 10–15 см, триває близько місяця.',
		price: '...',
	},
	{
		id: 4,
		imgMob: gorobynaImg1x_desk,
		imgMobRetina: gorobynaImg2x_desk,
		imgTab: gorobynaImg1x_desk,
		imgTabRetina: gorobynaImg2x_desk,
		title: 'Горобина проміжна',
		text: 'Витончене дерево з тонкими розкидистими пагонами, світлою корою, витонченою кроною. Після цвітіння білим кольором з’являються червоно-помаранчеві грони, які будуть до смаку місцевим птахам.',
		price: '...',
	},
	{
		id: 5,
		imgMob: matsudanaImg1x_desk,
		imgMobRetina: matsudanaImg2x_desk,
		imgTab: matsudanaImg1x_desk,
		imgTabRetina: matsudanaImg2x_desk,
		title: 'Верба Матсудана',
		text: 'Струнке швидкоросле дерево з ажурною, широкопірамідальною кpоною. Цвіте в квітні місяці. Молоді тонкі пагони - злегка опушені, жовтувато-оливкові, пізніше голі, коричневі. закручуються завжди по різному, немає двох однакових дерев.',
		price: '...',
	},
	{
		id: 6,
		imgMob: topolyaImg1x_desk,
		imgMobRetina: topolyaImg2x_desk,
		imgTab: topolyaImg1x_desk,
		imgTabRetina: topolyaImg2x_desk,
		title: 'Тополя пірамідальна',
		text: 'Швидкоросле високе дерево з вузькопірамідальною компактною кроною. Листя трикутне, загострене. Сережки червоного кольору. Зацвітає рано навесні, до розпускання листя приємно пахне.',
		price: '...',
	},
	{
		id: 7,
		imgMob: topolyaImg1x_desk,
		imgMobRetina: topolyaImg1x_desk,
		imgTab: topolyaImg1x_desk,
		imgTabRetina: topolyaImg1x_desk,
		title: 'Ялівець Стрікта',
		text: 'Густий конусоподібний, повільно зростаючий сорт ялівцю. Пагони ростуть вертикально. Хвоя зелено-блакитного кольору, колюча. Висота дорослої рослини - 2-3м.',
		price: '...',
	},
	{
		id: 8,
		imgMob: topolyaImg1x_desk,
		imgMobRetina: topolyaImg1x_desk,
		imgTab: topolyaImg1x_desk,
		imgTabRetina: topolyaImg1x_desk,
		title: 'Ялинка колюча формована',
		text: 'Формоване вічно зелене хвойне дерево округлої (подушкоподібної) форми. Крона щільна, густа і компактна, з характерним поглибленням посередині і вигнутими вгору пагонами. Зростає повільно.',
		price: '...',
	},
	{
		id: 9,
		imgMob: topolyaImg1x_desk,
		imgMobRetina: topolyaImg1x_desk,
		imgTab: topolyaImg1x_desk,
		imgTabRetina: topolyaImg1x_desk,
		title: 'Ялівець козацький формований',
		text: 'Формований вічнозелений, низький, розлогий хвойний кущ подушкоподібної форми, росте повільно. Голочки м’які, майже неколючі.',
		price: '...',
	},
];

export default data;
